export const PLAYFIELD_WIDTH = 920;
export const PLAYFIELD_GAME_WIDTH = 1080;
export const PLAYFIELD_HEIGHT = 1420;
export const PLAYFIELD_LEFT = (PLAYFIELD_GAME_WIDTH - PLAYFIELD_WIDTH) / 2;
export const PLAYFIELD_RIGHT = PLAYFIELD_LEFT + PLAYFIELD_WIDTH;
export const PLAYFIELD_TOP = 250;
export const PLAYFIELD_BOTTOM = PLAYFIELD_TOP + PLAYFIELD_HEIGHT;
