import { GAME_HEIGHT } from "./runtimeDimensions.ts";

export const PLAYFIELD_WIDTH = 980;
export const PLAYFIELD_GAME_WIDTH = 1080;
export const PLAYFIELD_LEFT = (PLAYFIELD_GAME_WIDTH - PLAYFIELD_WIDTH) / 2;
export const PLAYFIELD_RIGHT = PLAYFIELD_LEFT + PLAYFIELD_WIDTH;
export const PLAYFIELD_TOP = 212;
export const PLAYFIELD_BOTTOM_MARGIN = 148;
export const PLAYFIELD_HEIGHT = Math.max(
  1420,
  GAME_HEIGHT - PLAYFIELD_TOP - PLAYFIELD_BOTTOM_MARGIN,
);
export const PLAYFIELD_BOTTOM = PLAYFIELD_TOP + PLAYFIELD_HEIGHT;
